<?php
/**
 * Foxycom - eCommerce solutions
*
* Adroll
*
* @author    Foxycom <support@foxycom.com>
* @package   Foxycom_Adroll
* @copyright Copyright (c) 2017 Foxycom (https://foxycom.com)
* @license   https://foxycom.com/license/osl-30
*
* For the full copyright and license information, please view the LICENSE.txt
* file that was distributed with this source code.
*/
// @codingStandardsIgnoreFile
?>
<?php /** @var $block Foxycom\Adroll\Block\Product\Adroll */ ?>
<!-- BEGIN ADROLL PDP CODE -->
<script type="text/javascript">
//<![CDATA[
       <?php echo $block->getPdpCode();?>
//]]>
</script>
<!-- END OF ADROLL PDP CODE -->
